import 'package:hive/hive.dart';
import 'package:laser/app/data/models/payload.dart';

part 'register_response.g.dart'; // This file will be generated by running the Hive generator

@HiveType(typeId: 4)
class RegisterResponse extends HiveObject {
  @HiveField(0)
  late final bool status;

  @HiveField(1)
  late final bool error;

  @HiveField(2)
  late final String message;

  @HiveField(3)
  late final Payload payload;

  RegisterResponse({
    required this.status,
    required this.error,
    required this.message,
    required this.payload,
  });

  factory RegisterResponse.fromJson(Map<String, dynamic> json) {
    return RegisterResponse(
      status: json['status'],
      error: json['error'],
      message: json['message'],
      payload: Payload.fromJson(json['payload']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'status': status,
      'error': error,
      'message': message,
      'payload': payload.toJson(),
    };
  }

  RegisterResponse.fromData(
      {required this.status,
      required this.error,
      required this.message,
      required this.payload});
  // copyWith remains unchanged.
}
