import 'package:hive/hive.dart';
import 'package:laser/app/data/models/payload.dart';

part 'register_response.g.dart'; // This file will be generated by running the Hive generator

@HiveType(typeId: 2)
class RegisterResponse extends HiveObject {
  @HiveField(0)
  final bool? status;

  @HiveField(1)
  final bool? error;

  @HiveField(2)
  final String? err_message;

  @HiveField(3)
  final Payload? payload;

  RegisterResponse({
    this.status,
    this.error,
    this.err_message,
    this.payload,
  });

  factory RegisterResponse.fromJson(Map<String, dynamic> json) {
    return RegisterResponse(
      status: json['status'],
      error: json['error'],
      err_message: json['err_message'],
      payload: Payload.fromJson(json['payload'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'status': status,
      'error': error,
      'err_message': err_message,
      'payload': payload?.toJson(),
    };
  }

  RegisterResponse.fromData(
      {required this.status,
      required this.error,
      required this.err_message,
      this.payload});
  // copyWith remains unchanged.
}
